name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Run tests with pytest
      env:
        # Add all the variables your Settings class requires here
        URL: "postgresql+psycopg://benguar:dummypass@localhost/social"
        JWT_KEY: "JWT_SECRET_KEY"
        ALGORITHM: "JWT_ALGORITHM"
        REDIS_HOST: 'localhost'
        REDIS_PORT: 6379
        GROQ_API_KEY: 'groq_api_key_value'
      run: |
        pytest